[build]
  command = "npm run build"
  publish = "dist"
  base = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"